// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh3EyCm9mrxYg7YyN63mgWf5UYs2JcVOM',
    appId: '1:345077331175:web:3ff1d8356e063c45e19e42',
    messagingSenderId: '345077331175',
    projectId: 'miniproject-5b190',
    authDomain: 'miniproject-5b190.firebaseapp.com',
    storageBucket: 'miniproject-5b190.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHq4_HdRyvO5s0KttqQ8FrFHqXUeDrv4c',
    appId: '1:345077331175:android:de7f716bf5b0bf63e19e42',
    messagingSenderId: '345077331175',
    projectId: 'miniproject-5b190',
    storageBucket: 'miniproject-5b190.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsjZvyjazT8QCraSF8tfc-MHmX39-btSg',
    appId: '1:345077331175:ios:fe98754d89994ebbe19e42',
    messagingSenderId: '345077331175',
    projectId: 'miniproject-5b190',
    storageBucket: 'miniproject-5b190.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsjZvyjazT8QCraSF8tfc-MHmX39-btSg',
    appId: '1:345077331175:ios:9780aca046f077aae19e42',
    messagingSenderId: '345077331175',
    projectId: 'miniproject-5b190',
    storageBucket: 'miniproject-5b190.appspot.com',
    iosBundleId: 'com.example.flutterApplication2.RunnerTests',
  );
}
